---
version: '3.7'
services:
  instance-1:
    image: emqx/emqx:latest
    environment:
      EMQX_NAME: instance-1
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_dashboard"
    ports:
      - 1883:1883
      - 18083:18083

  instance-2:
    image: emqx/emqx:latest
    environment:
      EMQX_NAME: instance-2
      EMQX_LOADED_PLUGINS: "emqx_management,emqx_dashboard"
    ports:
      - 1884:1883
      - 18084:18083
