---
name: golang
on:
  - push
jobs:
  golangci:
    name: lint
    needs: go-projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  go:
    name: test
    needs: go-projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: docker-compose up -d
      - run: go test ./...
